# Generated by Django 4.2.20 on 2025-04-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_App.appointment'),
        ),
    ]
