# Generated by Django 4.2.20 on 2025-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
