# Generated by Django 4.2.20 on 2025-04-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_App', '0001_initial'),
        ('Doc_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMS_App.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_App.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS_App.patient')),
                ('tests', models.ManyToManyField(to='CMS_App.labtest')),
            ],
        ),
    ]
